# Generated by Django 6.0.3 on 2026-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clothingitemssize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingItemsSize',
            new_name='ClothingItemSize',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='clothing_item', through='main.ClothingItemSize', to='main.size'),
        ),
    ]
