# Generated by Django 6.0.3 on 2026-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_clothingitemssize_clothingitemsize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='clothing_items', through='main.ClothingItemSize', to='main.size'),
        ),
    ]
